android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
    - echo no | npm run build

script:


matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "10"
      script: "npm run tslint"
    - stage: "WebPack"
      os: osx
      env:
        - Webpack="iOS"
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      jdk: oraclejdk8
      script:
        - pod repo update
        - npm run build-ios-bundle
    - language: android
      os: linux
      env:
        - Webpack="Android"
      dist: trusty
      jdk: oraclejdk8
      before_install: nvm install 10
      script: npm run build-android-bundle
    - stage: "Build"
      env:
        - BuildAndroid="28"
      language: android
      os: linux
      jdk: oraclejdk8
      dist: trusty
      before_install: nvm install 10
      script:
        - tns build android
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
      jdk: oraclejdk8
      script:
        - pod repo update
        - tns build ios
